function navigate(pushPath) {
    window.location.href = pushPath;
}

const content = [
    {
        id: "1",
        title: "BEM-VINDO",
        image: "./assets/images/sp.jpeg",
        description: "Arial",
        address: "",
        operation: "",
        font: "",
    },
    {
        id: "2",
        title: "HISTORIA",
        image: "./assets/images/flagsp.png",
        description: "Arial",
        address: "",
        operation: "",
        font: "saopaulo.sp.gov.br",
    },
    {
        id: "3",
        title: "DICAS PONTOS",
        image: "./assets/images/light.png",
        description: "Arial",
        address: "",
        operation: "",
        font: "",
    },
    {
        id: "4",
        title: "OBRIGADO POR UTILIZAR",
        image: "./assets/images/logo.png",
        description: "Arial",
        address: "",
        operation: "",
        font: "",
    },
    {
        id: "5",
        title: "MASP",
        image: "./assets/images/MASP.png",
        description: "Arial",
        address: "Av. Paulista 1578 - Bela Vista, São Paulo",
        operation: "Horário de funcionamento: Seg a Ter das 10:00-20:00 e Qua a Dom das 10:00-18:00",
        font: "gazetasp.com.br",
    },
    {
        id: "6",
        title: "LIBERDADE",
        image: "./assets/images/liberdade.jpeg",
        description: "Arial",
        address: "R. Galvão Bueno",
        operation: "",
        font: "casavogue.globo.com",
    },
    {
        id: "7",
        title: "MERCADÃO DE SP",
        image: "./assets/images/mercadao.png",
        description: "Arial",
        address: "R. da Cantareira, 306 Centro histórico de São Paulo",
        operation: "Seg a Sáb das 06:00-18:00 e Dom das 06:00-16:00.",
        font: "meulugar.quintoandar",
    },
    {
        id: "8",
        title: "ESTAÇÃO DA LUZ",
        image: "./assets/images/estacao.jpeg",
        description: "Arial",
        address: "Praça da Luz,1 São Paulo",
        operation: "",
        font: "wikipédia",
    },
    {
        id: "9",
        title: "CATEDRAL DA SÉ",
        image: "./assets/images/catedral.jpg",
        description: "Arial",
        address: "Praça da Sé, Sé São Paulo",
        operation: "Seg a Dom: 8:00 ás 18:00",
        font: "wikipédia",
    },
    {
        id: "10",
        title: "GALERIA DO ROCK",
        image: "./assets/images/galeria.jpg",
        description: "Arial",
        address: "Av. São João, 439 - República, São Paulo",
        operation: "Seg a Qui: 9:00 ás 19:00 & Sáb: 09:00 ás 18:00",
        font: "wikipédia",
    },
    {
        id: "11",
        title: "FAVORITOS",
        image: "./assets/images/favorites.png",
        description: "Arial",
        address: "",
        operation: "",
        font: "",
    },

];
